elements = [
    {
        symbol: 'H',
        name: 'Hydrogen',
        category: 'Non-metal',
        'atomic-mass': 1.0078,
        'oxidation-states': ['±1'],
        isotopes: [{
            'mass-number': 1,
            'atomic-mass': 1.0078,
            abundance: .9998
        }, {
            'mass-number': 2,
            'atomic-mass': 2.0141,
            abundance: .0002
        }, {
            'mass-number': 3,
            'atomic-mass': 3.0160,
            abundance: 0
        }]
    },
    {
        symbol: 'He',
        name: 'Hydrogen',
        category: 'Noble-Gas',
        'atomic-mass': 4.0026,
        'oxidation-states': [],
        isotopes: [{
            'mass-number': 1,
            'atomic-mass': 1.0078,
            abundance: .9998
        }, {
            'mass-number': 2,
            'atomic-mass': 2.0141,
            abundance: .0002
        }, {
            'mass-number': 3,
            'atomic-mass': 3.0160,
            abundance: 0
        }]
    },
    {
        symbol: 'Li',
        name: 'Lithium',
        category: 'Alkali-Metal',
        'atomic-mass': 6.9410,
        'oxidation-states': ['+1'],
    },
    {
        symbol: 'Be',
        name: 'Beryllium',
        category: 'Alkali-Earth-Metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+2'],
    },
    {
        symbol: 'B',
        name: 'Boron',
        category: 'Metalloid',
        'atomic-mass': NaN,
        'oxidation-states': ['+3'],
    },
    {
        symbol: 'C',
        name: 'Carbon',
        category: 'Non-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['±4'],
    },
    {
        symbol: 'N',
        name: 'Nitrogen',
        category: 'Non-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['±3', '+5'],
    },
    {
        symbol: 'O',
        name: 'Oxygen',
        category: 'Non-metal',
        'atomic-mass': 15.999,
        'oxidation-states': ['-2'],
    },
    {
        symbol: 'F',
        name: 'Fluorine',
        category: 'Halogen',
        'atomic-mass': NaN,
        'oxidation-states': ['-1'],
    },
    {
        symbol: 'Ne',
        name: 'Neon',
        category: 'Noble-Gas',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Na',
        name: 'Sodium',
        category: 'Alkali-Metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+1'],
    },
    {
        symbol: 'Mg',
        name: 'Magnesium',
        category: 'Alkali-Earth-Metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+2'],
    },
    {
        symbol: 'Al',
        name: 'Aluminium',
        category: 'Post-Transition-Metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+3'],
    },
    {
        symbol: 'Si',
        name: 'Silicon',
        category: 'Metalloid',
        'atomic-mass': NaN,
        'oxidation-states': ['±4'],
    },
    {
        symbol: 'P',
        name: 'Phosphorous',
        category: 'Non-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['±3', 5],
    },
    {
        symbol: 'S',
        name: 'Sulfur',
        category: 'Non-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['±2', 4, 6],
    },
    {
        symbol: 'Cl',
        name: 'Chlorine',
        category: 'Halogen',
        'atomic-mass': NaN,
        'oxidation-states': ['±1', 3, 5, 7],
    },
    {
        symbol: 'Ar',
        name: 'Argon',
        category: 'Noble-Gas',
        'atomic-mass': NaN,
    },
    {
        symbol: 'K',
        name: 'Potassium',
        category: 'Alkali-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Ca',
        name: 'Calcium',
        category: 'Alkali-Earth-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Sc',
        name: 'Scandium',
        category: 'Rare-Earth-Metal',
        'atomic-mass': NaN,
    }, {
        symbol: 'Ti',
        name: 'Titanium',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    }, {
        symbol: 'Va',
        name: 'Vanadium',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    }, {
        symbol: 'Cr',
        name: 'Chromium',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    }, {
        symbol: 'Mn',
        name: 'Manganese',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    }, {
        symbol: 'Fe',
        name: 'Iron',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    }, {
        symbol: 'Co',
        name: 'Cobalt',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    }, {
        symbol: 'Ni',
        name: 'Nickel',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    },{
        symbol: 'Cu',
        name: 'Copper',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    },{
        symbol: 'Zn',
        name: 'Zinc',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Ga',
        name: 'Gallium',
        category: 'Post-Transition-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Ge',
        name: 'Germanium',
        category: 'Metalloid',
        'atomic-mass': NaN,
    },
    {
        symbol: 'As',
        name: 'Arsenic',
        category: 'Metalloid',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Se',
        name: 'Selenium',
        category: 'Non-metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Br',
        name: 'Bromine',
        category: 'Halogen',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Kr',
        name: 'Krypton',
        category: 'Noble-Gas',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Rb',
        name: 'Rubidium',
        category: 'Alkali-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Sr',
        name: 'Strontium',
        category: 'Alkali-Earth-Metal',
        'atomic-mass': NaN,
    },
    null, null, null, null, null, null, null, null, {
        symbol: 'Ag',
        name: 'Silver',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    },{
        symbol: 'Cd',
        name: 'Cadmium',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'In',
        name: 'Indium',
        category: 'Post-Transition-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Sn',
        name: 'Tin',
        category: 'Post-Transition-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Sb',
        name: 'Antimony',
        category: 'Metalloid',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Te',
        name: 'Tellurium',
        category: 'Metalloid',
        'atomic-mass': NaN,
    },
    {
        symbol: 'I',
        name: 'Iodine',
        category: 'Halogen',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Xe',
        name: 'Xenon',
        category: 'Noble-Gas',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Cs',
        name: 'Cesium',
        category: 'Alkali-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Ba',
        name: 'Barium',
        category: 'Alkali-Earth-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'La',
        name: 'Lanthanum',
        category: 'Rare-Earth-Metal',
        'atomic-mass': NaN,
    }, null, null, {
        symbol: 'Nd',
        name: 'Neodymium',
        category: 'Rare-Earth-Metal',
        'atomic-mass': NaN,
    }, null, null, null, null, null, {
        symbol: 'Dy',
        name: 'Dysprosium',
        category: 'Rare-Earth-Metal',
        'atomic-mass': NaN,
    }, null, null, null, {
        symbol: 'Yb',
        name: 'Ytterbium',
        category: 'Rare-Earth-Metal',
        'atomic-mass': NaN,
    },
    null, null, {
        symbol: 'W',
        name: 'Tungsten',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    }, null, null, null, null, {
        symbol: 'Pt',
        name: 'Platinum',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    },{
        symbol: 'Au',
        name: 'Gold',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    },{
        symbol: 'Hg',
        name: 'Mercury',
        category: 'Transition-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Tl',
        name: 'Thallium',
        category: 'Post-Transition-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Pb',
        name: 'Lead',
        category: 'Post-Transition-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Bi',
        name: 'Bismuth',
        category: 'Post-Transition-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Po',
        name: 'Polonium',
        category: 'Post-Transition-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'At',
        name: 'Astatine',
        category: 'Halogen',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Rn',
        name: 'Radon',
        category: 'Noble-Gas',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Fr',
        name: 'Francium',
        category: 'Alkali-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Ra',
        name: 'Radium',
        category: 'Alkali-Earth-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Ac',
        name: 'Actinium',
        category: 'Actinoid',
        'atomic-mass': NaN,
    }, {
        symbol: 'Th',
        name: 'Thorium',
        category: 'Actinoid',
        'atomic-mass': NaN,
    }, null, {
        symbol: 'U',
        name: 'Uranium',
        category: 'Actinoid',
        'atomic-mass': NaN,
    }, {
        symbol: 'Np',
        name: 'Neptunium',
        category: 'Actinoid',
        'atomic-mass': NaN,
    }, {
        symbol: 'Pu',
        name: 'Plutonium',
        category: 'Actinoid',
        'atomic-mass': NaN,
    }, {
        symbol: 'Am',
        name: 'Americium',
        category: 'Actinoid',
        'atomic-mass': NaN,
    }, null, null, null, null, null, null, {
        symbol: 'No',
        name: 'Nobelium',
        category: 'Actinoid',
        'atomic-mass': NaN,
    },
    null, null, null, null, null, null, null, null, null, null,
    {
        symbol: 'Rf',
        name: 'Rutherfordium',
        category: 'Post-Transition-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Db',
        name: 'Dubnium',
        category: 'Post-Transition-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Bi',
        name: 'Bismuth',
        category: 'Post-Transition-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Po',
        name: 'Polonium',
        category: 'Post-Transition-Metal',
        'atomic-mass': NaN,
    },
    {
        symbol: 'At',
        name: 'Astatine',
        category: 'Halogen',
        'atomic-mass': NaN,
    },
    {
        symbol: 'Rn',
        name: 'Radon',
        category: 'Noble-Gas',
        'atomic-mass': NaN,
    },
];