elements = [
    {
        symbol: 'H',
        name: 'Hydrogen',
        category: 'non-metal',
        'atomic-mass': 1.008,
        'oxidation-states': ['±1'],
        electronegativity: '2.20',
        isotopes: [{
            'mass-number': 1,
            'atomic-mass': 1.008,
            abundance: .9998
        }, {
            'mass-number': 2,
            'atomic-mass': 2.014,
            abundance: .0002
        }, {
            'mass-number': 3,
            'atomic-mass': 3.016,
            abundance: 0
        }],
        primordial: true,
        diatomic: true,
    },
    {
        symbol: 'He',
        name: 'Hydrogen',
        category: 'noble-gas',
        'atomic-mass': 4.003,
        'oxidation-states': [],
        isotopes: [{
            'mass-number': 3,
            'atomic-mass': 3.016,
            abundance: 0
        }, {
            'mass-number': 4,
            'atomic-mass': 4.003,
            abundance: 1
        }],
        primordial: true,
    },
    {
        symbol: 'Li',
        name: 'Lithium',
        category: 'alkali-metal',
        'atomic-mass': 6.941,
        'oxidation-states': ['+1'],
        electronegativity: '0.98',
        isotopes: [{
            'mass-number': 6,
            'atomic-mass': 6.015,
            abundance: 0.0759
        }, {
            'mass-number': 7,
            'atomic-mass': 7.016,
            abundance: 0.9241
        }],
        primordial: true,
    },
    {
        symbol: 'Be',
        name: 'Beryllium',
        category: 'alkali-earth-metal',
        'atomic-mass': 9.012,
        'oxidation-states': ['+2'],
        electronegativity: '1.57',
        primordial: true,
    },
    {
        symbol: 'B',
        name: 'Boron',
        category: 'metalloid',
        'atomic-mass': 10.81,
        'oxidation-states': ['+3'],
        electronegativity: '2.04',
        primordial: true,
    },
    {
        symbol: 'C',
        name: 'Carbon',
        category: 'non-metal',
        'atomic-mass': 12.01,
        'oxidation-states': ['±4'],
        electronegativity: '2.55',
        primordial: true,
        native: true,
    },
    {
        symbol: 'N',
        name: 'Nitrogen',
        category: 'non-metal',
        'atomic-mass': 14.01,
        'oxidation-states': ['-3'],
        electronegativity: '3.04',
        primordial: true,
        diatomic: true,
    },
    {
        symbol: 'O',
        name: 'Oxygen',
        category: 'non-metal',
        'atomic-mass': '16.00',
        'oxidation-states': ['-2', '-1'],
        primordial: true,
        diatomic: true,
    },
    {
        symbol: 'F',
        name: 'Fluorine',
        category: 'halogen',
        'atomic-mass': '19.00',
        'oxidation-states': ['-1'],
        primordial: true,
        diatomic: true,
    },
    {
        symbol: 'Ne',
        name: 'Neon',
        category: 'noble-gas',
        'atomic-mass': 20.18,
        primordial: true,
    },
    {
        symbol: 'Na',
        name: 'Sodium',
        category: 'alkali-metal',
        'atomic-mass': 22.99,
        'oxidation-states': ['+1'],
        primordial: true,
    },
    {
        symbol: 'Mg',
        name: 'Magnesium',
        category: 'alkali-earth-metal',
        'atomic-mass': 24.31,
        'oxidation-states': ['+2'],
        primordial: true,
    },
    {
        symbol: 'Al',
        name: 'Aluminium',
        category: 'post-transition-metal',
        'atomic-mass': 26.98,
        'oxidation-states': ['+3'],
        primordial: true,
        native: true,
    },
    {
        symbol: 'Si',
        name: 'Silicon',
        category: 'metalloid',
        'atomic-mass': 28.09,
        'oxidation-states': ['±4'],
        primordial: true,
        native: true,
    },
    {
        symbol: 'P',
        name: 'Phosphorous',
        category: 'non-metal',
        'atomic-mass': 30.97,
        'oxidation-states': ['±3', '+5'],
        'text-shrink': .9,
        primordial: true,
    },
    {
        symbol: 'S',
        name: 'Sulfur',
        category: 'non-metal',
        'atomic-mass': 32.06,
        'oxidation-states': ['±2', '+4', '+6'],
        primordial: true,
        native: true,
    },
    {
        symbol: 'Cl',
        name: 'Chlorine',
        category: 'halogen',
        'atomic-mass': 35.45,
        'oxidation-states': ['±1', '+3', '+5', '+7'],
        primordial: true,
        diatomic: true,
    },
    {
        symbol: 'Ar',
        name: 'Argon',
        category: 'noble-gas',
        'atomic-mass': 39.95,
        primordial: true,
    },
    {
        symbol: 'K',
        name: 'Potassium',
        category: 'alkali-metal',
        'atomic-mass': '+39.10',
        'oxidation-states': ['+1'],
        primordial: true,
    },
    {
        symbol: 'Ca',
        name: 'Calcium',
        category: 'alkali-earth-metal',
        'atomic-mass': 40.08,
        'oxidation-states': ['+2'],
        primordial: true,
    },
    {
        symbol: 'Sc',
        name: 'Scandium',
        category: 'transition-metal',
        'atomic-mass': 44.96,
        'oxidation-states': ['+3'],
        primordial: true,
    }, {
        symbol: 'Ti',
        name: 'Titanium',
        category: 'transition-metal',
        'atomic-mass': 47.87,
        'oxidation-states': ['+4'],
        primordial: true,
        native: true,
    }, {
        symbol: 'Va',
        name: 'Vanadium',
        category: 'transition-metal',
        'atomic-mass': 50.94,
        'oxidation-states': ['+5'],
        primordial: true,
        native: true,
    }, {
        symbol: 'Cr',
        name: 'Chromium',
        category: 'transition-metal',
        'atomic-mass': '+52.00',
        'oxidation-states': ['+3', '+6'],
        primordial: true,
        native: true,
    }, {
        symbol: 'Mn',
        name: 'Manganese',
        category: 'transition-metal',
        'atomic-mass': 54.94,
        'oxidation-states': ['+2', '+4', '+7'],
        primordial: true,
        native: true,
    }, {
        symbol: 'Fe',
        name: 'Iron',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+2', '+3'],
        native: true,
        primordial: true,
        magnetic: true,
    }, {
        symbol: 'Co',
        name: 'Cobalt',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+2', '+3'],
        primordial: true,
        native: true,
        magnetic: true,
    }, {
        symbol: 'Ni',
        name: 'Nickel',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+2'],
        primordial: true,
        native: true,
        magnetic: true,
    },{
        symbol: 'Cu',
        name: 'Copper',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+2'],
        primordial: true,
        native: true,
    },{
        symbol: 'Zn',
        name: 'Zinc',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+2'],
        primordial: true,
        native: true,
    },
    {
        symbol: 'Ga',
        name: 'Gallium',
        category: 'post-transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+2'],
        primordial: true,
    },
    {
        symbol: 'Ge',
        name: 'Germanium',
        category: 'metalloid',
        'atomic-mass': NaN,
        'oxidation-states': ['±4', '+2'],
        primordial: true,
    },
    {
        symbol: 'As',
        name: 'Arsenic',
        category: 'metalloid',
        'atomic-mass': NaN,
        'oxidation-states': ['±3', '+5'],
        primordial: true,
        native: true,
    },
    {
        symbol: 'Se',
        name: 'Selenium',
        category: 'non-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['±2', '+4', '+6'],
        primordial: true,
        native: true,
    },
    {
        symbol: 'Br',
        name: 'Bromine',
        category: 'halogen',
        'atomic-mass': NaN,
        'oxidation-states': ['±1', '+3', '+5'],
        primordial: true,
        diatomic: true,
    },
    {
        symbol: 'Kr',
        name: 'Krypton',
        category: 'noble-gas',
        'atomic-mass': NaN,
        'oxidation-states': ['+2'],
        primordial: true,
    },
    {
        symbol: 'Rb',
        name: 'Rubidium',
        category: 'alkali-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+1'],
        primordial: true,
    },
    {
        symbol: 'Sr',
        name: 'Strontium',
        category: 'alkali-earth-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+2'],
        primordial: true,
    },
    {
        symbol: 'Y',
        name: 'Yttrium',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+3'],
        primordial: true,
    }, null, null, null, {
        symbol: 'Tc',
        name: 'Technetium',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+4', '+7'],
        rare: true,
        radioactive: true,
    }, null, null, null, {
        symbol: 'Ag',
        name: 'Silver',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+1'],
        primordial: true,
    },{
        symbol: 'Cd',
        name: 'Cadmium',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+2'],
        primordial: true,
        native: true,
    },
    {
        symbol: 'In',
        name: 'Indium',
        category: 'post-transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+3'],
        primordial: true,
        native: true,
    },
    {
        symbol: 'Sn',
        name: 'Tin',
        category: 'post-transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['±4', '+2'],
        primordial: true,
        native: true,
    },
    {
        symbol: 'Sb',
        name: 'Antimony',
        category: 'metalloid',
        'atomic-mass': NaN,
        'oxidation-states': ['±3', '+5'],
        primordial: true,
        native: true,
    },
    {
        symbol: 'Te',
        name: 'Tellurium',
        category: 'metalloid',
        'atomic-mass': NaN,
        'oxidation-states': ['±2', '+4', '+6'],
        primordial: true,
        native: true,
    },
    {
        symbol: 'I',
        name: 'Iodine',
        category: 'halogen',
        'atomic-mass': NaN,
        'oxidation-states': ['±1', '+3', '+5', '+7'],
        primordial: true,
        diatomic: true,
    },
    {
        symbol: 'Xe',
        name: 'Xenon',
        category: 'noble-gas',
        'atomic-mass': NaN,
        'oxidation-states': ['+2', '+4', '+6'],
        primordial: true,
    },
    {
        symbol: 'Cs',
        name: 'Cesium',
        category: 'alkali-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+1'],
        primordial: true,
    },
    {
        symbol: 'Ba',
        name: 'Barium',
        category: 'alkali-earth-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+2'],
        primordial: true,
    },
    {
        symbol: 'La',
        name: 'Lanthanum',
        category: 'lanthanoid',
        'atomic-mass': NaN,
        'oxidation-states': ['+3'],
        primordial: true,
    }, null, null, {
        symbol: 'Nd',
        name: 'Neodymium',
        category: 'lanthanoid',
        'atomic-mass': NaN,
        'oxidation-states': ['+3'],
        primordial: true,
    }, null, null, null, null, null, {
        symbol: 'Dy',
        name: 'Dysprosium',
        category: 'lanthanoid',
        'atomic-mass': NaN,
        'oxidation-states': ['+3'],
        primordial: true,
    }, null, null, null, {
        symbol: 'Yb',
        name: 'Ytterbium',
        category: 'lanthanoid',
        'atomic-mass': NaN,
        'oxidation-states': ['+3'],
        primordial: true,
    },
    {
        symbol: 'Lu',
        name: 'Lutetium',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+3'],
        primordial: true,
    }, null, {
        symbol: 'W',
        name: 'Tungsten',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+4', '+6'],
        primordial: true,
        native: true,
    }, null, null, null, null, {
        symbol: 'Pt',
        name: 'Platinum',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+2', '+4'],
        primordial: true,
        native: true,
    },{
        symbol: 'Au',
        name: 'Gold',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+3'],
        primordial: true,
        native: true,
    },{
        symbol: 'Hg',
        name: 'Mercury',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+1', '+2'],
        primordial: true,
        native: true,
    },
    {
        symbol: 'Tl',
        name: 'Thallium',
        category: 'post-transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+1', '+3'],
        primordial: true,
    },
    {
        symbol: 'Pb',
        name: 'Lead',
        category: 'post-transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+2', '+4'],
        primordial: true,
        native: true,
    },
    {
        symbol: 'Bi',
        name: 'Bismuth',
        category: 'post-transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['+3'],
        radioactive: true,
        primordial: true,
        native: true,
    },
    {
        symbol: 'Po',
        name: 'Polonium',
        category: 'post-transition-metal',
        'atomic-mass': NaN,
        'oxidation-states': ['-2', '+2', '+4'],
        rare: true,
        radioactive: true,
    },
    {
        symbol: 'At',
        name: 'Astatine',
        category: 'halogen',
        'atomic-mass': NaN,
        'oxidation-states': ['-1', '+1'],
        rare: true,
        radioactive: true,
    },
    {
        symbol: 'Rn',
        name: 'Radon',
        category: 'noble-gas',
        'atomic-mass': NaN,
        rare: true,
        radioactive: true,
    },
    {
        symbol: 'Fr',
        name: 'Francium',
        category: 'alkali-metal',
        'atomic-mass': NaN,
        rare: true,
        radioactive: true,
    },
    {
        symbol: 'Ra',
        name: 'Radium',
        category: 'alkali-earth-metal',
        'atomic-mass': NaN,
        rare: true,
        radioactive: true,
    },
    {
        symbol: 'Ac',
        name: 'Actinium',
        category: 'actinoid',
        'atomic-mass': NaN,
        rare: true,
        radioactive: true,
    }, {
        symbol: 'Th',
        name: 'Thorium',
        category: 'actinoid',
        'atomic-mass': NaN,
        radioactive: true,
        primordial: true,
    }, null, {
        symbol: 'U',
        name: 'Uranium',
        category: 'actinoid',
        'atomic-mass': NaN,
        radioactive: true,
        primordial: true,
    }, {
        symbol: 'Np',
        name: 'Neptunium',
        category: 'actinoid',
        'atomic-mass': NaN,
        rare: true,
        radioactive: true,
    }, {
        symbol: 'Pu',
        name: 'Plutonium',
        category: 'actinoid',
        'atomic-mass': NaN,
        rare: true,
        radioactive: true,
    }, {
        symbol: 'Am',
        name: 'Americium',
        category: 'actinoid',
        'atomic-mass': NaN,
        synthetic: true,
        radioactive: true,
    }, null, null, null, null, null, null, {
        symbol: 'No',
        name: 'Nobelium',
        category: 'actinoid',
        'atomic-mass': NaN,
        radioactive: true,
        synthetic: true,
    },
    {
        symbol: 'Rf',
        name: 'Rutherfordium',
        category: 'transition-metal',
        'atomic-mass': NaN,
        'text-shrink': .8,
        synthetic: true,
        radioactive: true,
    },
    {
        symbol: 'Db',
        name: 'Dubnium',
        category: 'transition-metal',
        'atomic-mass': NaN,
        synthetic: true,
        radioactive: true,
    },
    null, null, null, null, null, null, null, null,
    null, null, null, null, null, null
];